export type Offering={slug:string;title:string;eyebrow:string;image:string;alt:string;description:string;intro:string;details:string[];specs?:[string,string][];group:'marquees'|'weddings'|'event-essentials'|'services';contain?:boolean};
export const offerings:Offering[]=[
{slug:'universal-marquee',title:'Universal Marquees',eyebrow:'A beautifully flexible beginning',image:'garden-marquee.jpg',alt:'White Eventco marquee with glass sides in a garden setting',description:'Versatile spaces for intimate celebrations, garden parties and public events.',intro:'A simple idea, shaped around your occasion. Our Universal range gives you a flexible clear-span space with a choice of finishes to make it your own.',details:['Choose white or clear soft walls, with a solid glass upgrade available.','Add an integrated solid wood floor to complete your space.','A practical choice for shows, markets, ceremonies and smaller weddings.'],specs:[['Widths','3m, 6m, 9m, 12m or 15m'],['Length','Configured in 3m bays'],['Eave height','2.4m or 3m'],['Wall options','White, clear PVC or upgraded glass']],group:'marquees'},
{slug:'premium-structures',title:'Premium Structures',eyebrow:'An exceptional space to gather',image:'classic-wedding.jpg',alt:'Elegant dining setting inside an Eventco premium wedding marquee',description:'Refined structures, generous proportions and a high-quality finish throughout.',intro:'Create room for something ambitious. Our Premium range combines contemporary structures with solid flooring and enhanced thermal qualities for a comfortable event setting.',details:['Choose an A-frame or contemporary curved roof.','Solid cassette flooring can accommodate uneven ground, subject to a site assessment.','Glass, solid and insulated walling options suit a range of events and longer installations.'],specs:[['Widths','5m, 10m, 12m, 15m, 20m or 25m'],['Length','Configured in 5m bays; subject to site suitability'],['Eave height','3m or 4m'],['Roof options','White, clear or thermally insulated']],group:'marquees'},
{slug:'ivy-pavilion-orangery',title:'The Ivy Pavilion Orangery',eyebrow:'Architectural by nature',image:'orangery-daylight.jpg',alt:'Black-framed glass orangery with dressed tables and greenery',description:'Distinctive black framing. Beautiful glass walls. A setting with a sense of occasion.',intro:'Let the outside become part of your celebration. The Ivy Pavilion pairs striking black frames with architectural glass to create an extraordinary setting for weddings and hospitality.',details:['Choose a fully clear roof and glass walls, or a solid roof finish.','Available for individual events, long-term hire and venue installations.','Thermal options include double glazing, insulated wall panels and insulated roofs.'],specs:[['Widths','15m or 20m'],['Length','5m bay increments, up to 35m'],['Eave height','3m or 4m; 20m width on 3m legs only'],['Finish','Black architectural framing and glazing']],group:'marquees'},
{slug:'weddings/rustic-love',title:'Rustic Love',eyebrow:'Naturally, beautifully you',image:'clear-roof-wedding.jpg',alt:'Long wooden tables and crossback chairs beneath a clear marquee roof',description:'Warm wood, soft candlelight and a little of the outdoors.',intro:'For celebrations that feel close to nature. Bring an intimate, relaxed atmosphere to a woodland setting, family farm or garden with natural textures and thoughtful details.',details:['Build your look around wooden furniture and natural colour.','Make the most of the setting with clear roof sections.','Share your inspiration with our team to shape your own wedding style.'],group:'weddings'},
{slug:'weddings/classic',title:'The Classic',eyebrow:'Timeless for a reason',image:'classic-wedding.jpg',alt:'Classic ivory wedding tables with white flowers and elegant chairs',description:'Elegant interiors and considered details that never go out of style.',intro:'A light-filled setting for a day you will always remember. Soft ivory linings, beautifully dressed tables and complementary furniture create a timeless backdrop.',details:['Explore pleated ivory, flat contemporary or clear roof finishes.','Choose furniture that complements your flowers and table styling.','Create a graceful setting at home or on a country estate.'],group:'weddings'},
{slug:'weddings/the-statement',title:'The Statement',eyebrow:'For a day like no other',image:'orangery-evening.jpg',alt:'Glass orangery dining room lit for an evening celebration',description:'Atmospheric lighting and a celebration with your signature on it.',intro:'A space with presence, from the first arrival to the final dance. Explore luxurious finishes and expressive details to give your celebration its own personality.',details:['Discuss chandeliers, mood lighting and starlight ceilings.','Pair statement furniture with your chosen décor.','Complete your plans with luxury restrooms and the practical event essentials.'],group:'weddings'},
{slug:'event-essentials/furniture-hire',title:'Furniture Hire',eyebrow:'Take your seat',image:'chiavari-chair.jpg',alt:'Limewash Chiavari chair available from Eventco',description:'Chairs and tables for dining, mingling and making memories.',intro:'The right furniture makes a space feel welcoming. Explore seating, banquet tables, trestle tables and poseur tables for your event.',details:['Limewash Chiavari chairs for a classic dining setting.','Round banquet and rectangular trestle tables.','Glass poseur tables for drinks receptions and informal gatherings.'],group:'event-essentials',contain:true},
{slug:'event-essentials/heating-cooling',title:'Heating & Cooling',eyebrow:'Comfort in every season',image:'portable-cooling.jpg',alt:'Portable cooling unit with directional air outlets',description:'A comfortable space, from the first arrival to the last dance.',intro:'Help your guests feel at home whatever the season. Talk to the team about heating and cooling for your space, guest numbers and event plans.',details:['Climate control options for your event setting.','Advice based on the structure and time of year.','Available with a marquee or as a standalone hire.'],group:'event-essentials',contain:true},
{slug:'event-essentials/generators-power',title:'Generators & Power',eyebrow:'Behind every great event',image:'eventco-generator.jpg',alt:'Eventco-branded mobile power generator',description:'Power for the lighting, catering and moments that matter.',intro:'Bring together your power requirements from the outset. We can help you plan generator and electrical distribution hire around the equipment your event needs.',details:['Generator hire for event power requirements.','Power distribution equipment.','Share your lighting, catering and supplier requirements when you enquire.'],group:'event-essentials'},
{slug:'event-essentials/crowd-barriers',title:'Crowd Barriers',eyebrow:'A considered welcome',image:'crowd-barriers.jpg',alt:'Interlocking steel crowd barriers',description:'Give queues, entrances and event boundaries a clear structure.',intro:'Make space for a smooth arrival. Crowd barriers help organise entrances, queues and designated areas around your event.',details:['Interlocking barriers for temporary event layouts.','Discuss quantities and placement with our team.','Hire independently or alongside your marquee.'],group:'event-essentials'},
{slug:'event-essentials/picket-fencing',title:'Picket Fencing',eyebrow:'The finishing boundary',image:'picket-fencing.jpg',alt:'White picket fencing beside an Eventco event structure',description:'A neat finishing touch for outdoor spaces and hospitality areas.',intro:'Define an outdoor space with a softer finish. White picket fencing brings a considered boundary to your marquee surroundings.',details:['Define gardens, hospitality areas and guest spaces.','Pair with your marquee or arrange standalone hire.','Share your proposed layout to discuss quantities.'],group:'event-essentials'},
{slug:'event-essentials/track-matting',title:'Track Matting',eyebrow:'A better way in',image:'track-matting.jpg',alt:'Temporary track matting laid over grass',description:'Practical access across outdoor ground.',intro:'Think about the journey to your event as well as the space itself. Temporary matting helps you plan routes across outdoor areas.',details:['Temporary surface options for outdoor event access.','Discuss the ground conditions and intended use with our team.','Available as an individual hire or part of your event requirements.'],group:'event-essentials'},
{slug:'industrial-structures',title:'Industrial Structures',eyebrow:'Space for what comes next',image:'industrial-structure.jpg',alt:'Eventco industrial structure for additional operational space',description:'Flexible, semi-permanent space for business, education and essential services.',intro:'When you need more room, start with the way you work. We provide adaptable structures for storage, production, learning and temporary facilities.',details:['Warehousing, logistics and manufacturing: layouts with access doors, lighting and heating options.','Schools and canteens: extra room for dining, classes or sports facilities.','Healthcare and emergency uses: temporary waiting areas, canteens and shelter solutions.'],group:'services'},
{slug:'luxury-loo-hire',title:'Luxury Loo Hire',eyebrow:'Consider every comfort',image:'luxury-loo-interior.jpg',alt:'Luxury restroom interior from Eventco',description:'A thoughtful finishing touch for the comfort of your guests.',intro:'Every part of your event should feel considered. Include luxury toilet hire in your plans for weddings, private celebrations and corporate hospitality.',details:['Discuss your guest numbers and event duration.','Plan the location and access with your wider event layout.','Speak to the team about the most suitable unit and arrangements.'],group:'services'},
{slug:'stage-hire',title:'Stage Hire',eyebrow:'Set the scene',image:'stage-hire.jpg',alt:'Eventco stage installed for a performance',description:'A platform for the performance, presentation or celebration.',intro:'From a school production to an outdoor festival, create a stage around the occasion. Our range includes indoor staging, theatre extensions and roofed outdoor stages.',details:['Discuss the height, width and size your performance needs.','Indoor and outdoor staging solutions.','Access ramping options can be included in the event plan.'],group:'services'},
];
export const marqueeItems=offerings.filter(x=>x.group==='marquees');
export const weddingItems=offerings.filter(x=>x.group==='weddings');
export const essentials=offerings.filter(x=>x.group==='event-essentials');
export const extraServices=offerings.filter(x=>x.group==='services');
export const imagePath=(name:string)=>'/previews/eventco/images/'+name;
export function enquiryHref(service:string){return '/contact?service='+encodeURIComponent(service)}
