import {ArrowRight,ArrowUpRight,Check,MoveDown} from 'lucide-react';
import {type Offering,imagePath,enquiryHref} from './content';
export function CTA({title='Let’s make something remarkable.',text='Tell us what you have in mind. We’ll help you find the right space and bring the details together.',service=''}:{title?:string;text?:string;service?:string}){return <section className="cta-band"><img className="cta-photo" src="/previews/eventco/images/coastal-marquee.jpg" alt="" loading="lazy" width="1440" height="960"/><div className="wrap cta-inner"><div><div className="eyebrow">Let’s make it happen</div><h2>{title}</h2><p>{text}</p></div><a className="round-link cta-orbit" href={enquiryHref(service)}><span>Plan your<br/>event</span><ArrowUpRight/></a></div></section>}
export function Card({item,index=0}:{item:Offering;index?:number}){return <a className={'service-card '+(item.contain?'product-card':'')} href={'/'+item.slug}><div className="card-image"><img src={imagePath(item.image)} alt={item.alt} loading="lazy" width="800" height="600"/><span className="card-arrow" aria-hidden="true"><ArrowUpRight/></span></div><div className="card-meta"><span className="eyebrow">{String(index+1).padStart(2,'0')} / {item.eyebrow}</span><h3>{item.title}</h3><p>{item.description}</p></div></a>}
export function Breadcrumb({items}:{items:[string,string][]}){return <nav className="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a>{items.map(([name,url],i)=><span key={url}><span aria-hidden="true">/</span>{i===items.length-1?<span aria-current="page">{name}</span>:<a href={url}>{name}</a>}</span>)}</nav>}
export function PageIntro({eyebrow,title,italic,description}:{eyebrow:string;title:string;italic:string;description:string}){return <section className="wrap page-intro"><div className="eyebrow">{eyebrow}</div><div className="page-intro-row"><h1>{title}<br/><em>{italic}</em></h1><p>{description}</p></div></section>}
export function Steps(){return <section className="wrap section process"><div><div className="eyebrow">The Eventco approach</div><h2>From first idea<br/>to <em>final detail.</em></h2><a href="/contact" className="text-link">Start the conversation<ArrowRight/></a></div><div className="steps">{[['01','Tell us your vision','Your date, your setting, your ideas. Every good event starts with a conversation.'],['02','Make it your own','Explore the structure, layout and finishing touches that bring it all together.'],['03','Bring it to life','A team with the experience to turn considered plans into an unforgettable setting.']].map(([n,t,p])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}</div></section>}
export function TickList({items}:{items:string[]}){return <ul className="tick-list">{items.map(x=><li key={x}><Check size={18}/><span>{x}</span></li>)}</ul>}
export function PhotoHero({image,alt,eyebrow,title,italic,description,service}:{image:string;alt:string;eyebrow:string;title:string;italic:string;description:string;service:string}){return <section className="hero secondary-hero"><img className="hero-image" src={imagePath(image)} alt={alt} fetchPriority="high"/><div className="hero-content"><div className="eyebrow">{eyebrow}</div><h1>{title}<br/><em>{italic}</em></h1><p>{description}</p><div className="actions"><a className="button light" href={enquiryHref(service)}>Let’s start planning<ArrowUpRight/></a><a className="hero-scroll" href="#explore">Explore<MoveDown size={16}/></a></div></div></section>}
export function Testimonial(){return <section className="testimonial wrap"><div className="eyebrow">A few words from our couples</div><span className="quote-mark" aria-hidden="true">“</span><blockquote>No ask was too big for Johnny and the team and it was exactly as we wanted it.</blockquote><div className="quote-credit">Zara H <span>Wedding client</span></div><a className="review-source" href="https://eventcomarquees.com/" target="_blank" rel="noreferrer">From Eventco’s customer reviews ↗</a></section>}
